name: methylkit
channels:
    - conda-forge
    - bioconda
    - defaults
    - r
dependencies:
    - r-base=4.1.3
    - bioconductor-methylkit=1.20.0
    - bioconductor-genomation=1.26.0
    - r-tidyverse=1.3.2
